apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moj-python-app
  template:
    metadata:
      labels:
        app: moj-python-app
    spec:
      containers:
      - name: python-container
        image: moj-python-app
        imagePullPolicy: Never
